"""Core data models for the latency arbitrage bot."""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class SignalType(str, Enum):
    SPORTS_SCORE = "sports_score"
    SPORTS_STATUS = "sports_status"
    WEATHER_ALERT = "weather_alert"
    WEATHER_TEMPERATURE = "weather_temperature"
    WEATHER_WIND = "weather_wind"
    NEWS_BREAKING = "news_breaking"
    NEWS_SENTIMENT = "news_sentiment"
    CRYPTO_PRICE = "crypto_price"
    CUSTOM = "custom"


class MarketSide(str, Enum):
    YES = "yes"
    NO = "no"
    BUY = "buy"
    SELL = "sell"


class OrderType(str, Enum):
    LIMIT = "limit"
    MARKET = "market"


class OrderStatus(str, Enum):
    PENDING = "pending"
    SUBMITTED = "submitted"
    FILLED = "filled"
    PARTIALLY_FILLED = "partially_filled"
    CANCELLED = "cancelled"
    REJECTED = "rejected"
    EXPIRED = "expired"


class Platform(str, Enum):
    POLYMARKET = "polymarket"
    KALSHI = "kalshi"


class BotMode(str, Enum):
    PAPER = "paper"
    LIVE = "live"


@dataclass
class DataSignal:
    """A signal from a data source indicating new information."""
    source: str
    signal_type: SignalType
    event_id: str
    data: dict[str, Any]
    timestamp_ms: int = field(default_factory=lambda: int(time.time() * 1000))
    confidence: float = 1.0
    raw_payload: dict[str, Any] | None = None

    @property
    def age_ms(self) -> int:
        return int(time.time() * 1000) - self.timestamp_ms

    @property
    def is_stale(self) -> bool:
        return self.age_ms > 5000  # Default 5s staleness


@dataclass
class MarketState:
    """Current state of a prediction market."""
    platform: Platform
    market_id: str
    question: str
    yes_price: float
    no_price: float
    volume_24h: float = 0.0
    liquidity: float = 0.0
    last_updated_ms: int = field(default_factory=lambda: int(time.time() * 1000))
    metadata: dict[str, Any] = field(default_factory=dict)
    order_book: OrderBook | None = None

    @property
    def spread(self) -> float:
        return abs(self.yes_price + self.no_price - 1.0)

    @property
    def midpoint(self) -> float:
        return self.yes_price  # yes_price is the implied probability


@dataclass
class OrderBookLevel:
    price: float
    size: float


@dataclass
class OrderBook:
    bids: list[OrderBookLevel] = field(default_factory=list)
    asks: list[OrderBookLevel] = field(default_factory=list)
    timestamp_ms: int = field(default_factory=lambda: int(time.time() * 1000))

    @property
    def best_bid(self) -> float | None:
        return self.bids[0].price if self.bids else None

    @property
    def best_ask(self) -> float | None:
        return self.asks[0].price if self.asks else None

    @property
    def spread(self) -> float | None:
        if self.best_bid is not None and self.best_ask is not None:
            return self.best_ask - self.best_bid
        return None

    def depth_at_price(self, price: float, side: MarketSide) -> float:
        levels = self.bids if side in (MarketSide.BUY, MarketSide.YES) else self.asks
        return sum(lvl.size for lvl in levels if lvl.price >= price) if side in (MarketSide.BUY, MarketSide.YES) else sum(lvl.size for lvl in levels if lvl.price <= price)


@dataclass
class TradeSignal:
    """An actionable trade signal generated by the arbitrage engine."""
    signal_id: str
    data_signal: DataSignal
    market: MarketState
    platform: Platform
    market_id: str
    side: MarketSide
    target_price: float
    fair_value: float
    edge: float  # fair_value - market_price (the alpha)
    confidence: float
    suggested_size_usd: float
    timestamp_ms: int = field(default_factory=lambda: int(time.time() * 1000))
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def is_actionable(self) -> bool:
        return self.edge > 0 and self.confidence > 0.5 and not self.data_signal.is_stale


@dataclass
class Order:
    """An order to be placed on a prediction market."""
    order_id: str
    trade_signal: TradeSignal
    platform: Platform
    market_id: str
    side: MarketSide
    order_type: OrderType
    price: float
    size: float  # in contracts or USD
    status: OrderStatus = OrderStatus.PENDING
    submitted_at_ms: int | None = None
    filled_at_ms: int | None = None
    fill_price: float | None = None
    fill_size: float | None = None
    fees: float = 0.0
    platform_order_id: str | None = None
    error_message: str | None = None

    @property
    def latency_ms(self) -> int | None:
        if self.submitted_at_ms and self.filled_at_ms:
            return self.filled_at_ms - self.submitted_at_ms
        return None


@dataclass
class Position:
    """A current position in a prediction market."""
    platform: Platform
    market_id: str
    side: MarketSide
    size: float
    avg_entry_price: float
    current_price: float = 0.0
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0
    orders: list[Order] = field(default_factory=list)

    @property
    def total_pnl(self) -> float:
        return self.unrealized_pnl + self.realized_pnl

    def update_pnl(self, current_price: float) -> None:
        self.current_price = current_price
        if self.side in (MarketSide.YES, MarketSide.BUY):
            self.unrealized_pnl = (current_price - self.avg_entry_price) * self.size
        else:
            self.unrealized_pnl = (self.avg_entry_price - current_price) * self.size


@dataclass
class LatencyMeasurement:
    """Tracks latency between a data source and a market platform."""
    source: str
    platform: Platform
    signal_timestamp_ms: int
    market_update_ms: int

    @property
    def latency_ms(self) -> int:
        return self.market_update_ms - self.signal_timestamp_ms
